name    'BradChesney79-intel_graphics_install'
version '2.0.0'
source 'https://github.com/bradchesney79/intel_graphics_install'
author 'Brad Chesney'
license 'Creative Commons'
summary 'Install the Intel provided linux graphics kernel drivers'
description 'Intel provides drivers for their video chipsets, the experience is better with the new and improved capabilities, so make it easier to take advantage of their kindness.'

## Dependencies:
dependency 'puppetlabs/apt', '1.5.2'
